version: "3.8"
name: popug-task-tracker
services:

  mongodb:
    image: aashreys/mongo-auth:latest
    hostname: "mongodb"
    restart: always
    ports:
      - 42017:27017
    environment:
      AUTH: yes
      MONGODB_ADMIN_USER: popug-admin
      MONGODB_ADMIN_PASS: kmge4CxsdWEZ2g45
      MONGODB_APPLICATION_DATABASE: popug
      MONGODB_APPLICATION_USER: popug
      MONGODB_APPLICATION_PASS: yEjGKPpfFLza8Zk3
    volumes:
      - mongo-data:/data/db

  rabbit:
    image: "rabbitmq:3.10-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "popug"
      RABBITMQ_DEFAULT_PASS: "yEjGKPpfFLza8Zk3"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 42672:5672
      - 42673:15672

volumes:
  mongo-data:
